name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

jobs:
  monkci-remote-cache:
    name: Monk CI with Remote Cache
    runs-on: monkci-ubuntu-24.04-4
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: ~/.gradle/init.gradle
          old-string: "if (!settings.buildCache?.remote) {"
          new-string: "if (true) {"
      - run: ./gradlew --build-cache build -x test

  monkci-cacheless:
    name: Monk CI Cacheless
    runs-on: monkci-ubuntu-24.04-4
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build -x test

  github-local-cache:
    name: Github with Local Cache
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    env:
      GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - run: ./gradlew --build-cache build -x test

  github-cacheless:
    name: Github Cacheless
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-disabled: true
      - run: ./gradlew build -x test
